# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            "Git Commit \n\n Patch"
tagline:          'Git Commit Patch'
description:      'A collection of posts and projects by <a href="http://linkedin.com/in/olitreadwell" target="_blank">Oli Treadwell</a>'
url:              http://olitreadwell.github.io
baseurl:          /

author:
  name:           'Oli Treadwell'
  url:            https://linkedin.com/in/olitreadwell

paginate:         3

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/olitreadwell/olitreadwell.github.io
