# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Oli Treadwell
tagline:          'Small Changes'
description:      'A collection of posts and projects by <a href="http://linkedin.com/in/olitreadwell" target="_blank">Oli Treadwell</a>'
url:              http://olitreadwell.github.io
baseurl:          /

author:
  name:           'Oli Treadwell'
  url:            https://twitter.com/olitreadwell

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/olitreadwell/olitreadwell.github.io
